### ISSUE TITLE
Shader compilation error on my machine

### ISSUE THREAD

**Issue by darkf** [sheepandshepherd/geotool#1]
Using an Intel integrated GPU, probably why. The error:

	glamour.shader.ShaderException@..\..\AppData\Roaming\dub\packages\glamour-1.0.1\glamour\glamour\shader.d(74): ERROR: 0:23: 'texture2D' : function is removed in Forward Compatible context
	ERROR: 0:23: 'texture2D' : no matching overloaded function found (using implicit conversion)
	ERROR: 0:23: 'rgba' : field selection requires structure, vector, or matrix on left hand side
	ERROR: 0:23: '=' :  cannot convert from 'const float' to '4-component vector of float'

	 ?
	Failed to link shader: texturedrect.

Dunno why, the texture2D call looks fine to me.

**Comment by darkf** [comment]
Oh, per the:

    glamour.shader.ShaderException@..\..\AppData\Roaming\dub\packages\glamour-1.0.1\glamour\glamour\shader.d(74): ERROR: 0:76: 'texture2D' : function is removed in Forward Compatible context

It's now `texture`, not `texture2D`. Changing those calls in all shaders works.

**Comment by sheepandshepherd** [comment]
Thanks! Should be fixed by ae66fc1a37ec4bc57fc8b6aa1b495b0e38e4421a. There's still a lot of old code left from when this used OpenGL 2.0. The NVidia driver ignores deprecation errors sometimes, unlike Intel and AMD.
